
name: 'Build Docs'

on:
  push:
    branches:
      - 'main'
      - 'master'
  schedule:
    # rebuild docs at 10 AM every Monday
    - cron:  '0 10 * * 1'

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Show env
        run: 'env | sort -u'
      - name: Install Roswell
        env:
          LISP: sbcl-bin
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          echo /home/runner/.roswell/bin >> $GITHUB_PATH
      - name: Check CL Version
        run: |
          ros install 40ants/cl-info
          cl-info
      - name: Install Qlot
        run: ros install qlot
      - name: Install Dependencies
        run: qlot install
      - name: Build docs
        run: qlot exec docs/scripts/build.ros
      - name: Check git output
        run: |
          git status
          git branch -a
          git rev-parse --abbrev-ref --symbolic-full-name '@{u}'
      - name: Upload docs
        run: qlot exec roswell/gh-pages.ros docs/build/
        env:
          # This token is automaticall added to the secrets
          # by GitHub. Read more here:
          # https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Readme should be pushed to the main branch
      - name: Upload updated README
        run: |
          git add README.md
          git commit -m 'Automatic README update.'
          git push
